/**
 * Hollow Row's solid geometry — generated by tools/gen_cemetery.py.
 *
 * The client builds its meshes from this array and the server derives its
 * occluders from the same entries, so the thing you see and the thing that
 * stops a bullet cannot drift apart. `kind` only selects a material.
 */
export interface CemeteryBlock {
  /** Footprint centre. */
  x: number;
  z: number;
  /** Footprint size on x and z, and height from the ground. */
  w: number;
  d: number;
  h: number;
  kind: "wall" | "pillar" | "altar" | "gable" | "tomb" | "plot" | "shed" | "obelisk" | "tree";
}

export const CEMETERY_BLOCKS: CemeteryBlock[] = [
  { x: 0.0, z: -24.6, w: 60.0, d: 0.8, h: 2.8, kind: "wall" }, // perim_s
  { x: 0.0, z: 24.6, w: 60.0, d: 0.8, h: 2.8, kind: "wall" }, // perim_n
  { x: -29.6, z: 0.0, w: 0.8, d: 50.0, h: 2.8, kind: "wall" }, // perim_w
  { x: 29.6, z: 0.0, w: 0.8, d: 50.0, h: 2.8, kind: "wall" }, // perim_e
  { x: -25.5, z: 4.0, w: 9.0, d: 0.7, h: 3.2, kind: "wall" }, // chapel_s_a
  { x: -10.5, z: 4.0, w: 13.0, d: 0.7, h: 3.2, kind: "wall" }, // chapel_s_b
  { x: -4.0, z: 9.5, w: 0.7, d: 11.0, h: 3.2, kind: "wall" }, // chapel_e_a
  { x: -4.0, z: 22.0, w: 0.7, d: 6.0, h: 3.2, kind: "wall" }, // chapel_e_b
  { x: 6.5, z: 4.0, w: 5.0, d: 0.7, h: 3.2, kind: "wall" }, // alley_s_a
  { x: 21.5, z: 4.0, w: 17.0, d: 0.7, h: 3.2, kind: "wall" }, // alley_s_b
  { x: 4.0, z: 11.5, w: 0.7, d: 15.0, h: 3.2, kind: "wall" }, // alley_w_a
  { x: 4.0, z: 24.0, w: 0.7, d: 2.0, h: 3.2, kind: "wall" }, // alley_w_b
  { x: -26.5, z: -4.0, w: 7.0, d: 0.7, h: 3.2, kind: "wall" }, // plots_n_a
  { x: -11.5, z: -4.0, w: 15.0, d: 0.7, h: 3.2, kind: "wall" }, // plots_n_b
  { x: -4.0, z: -21.75, w: 0.7, d: 6.5, h: 3.2, kind: "wall" }, // plots_e_a
  { x: -4.0, z: -9.25, w: 0.7, d: 10.5, h: 3.2, kind: "wall" }, // plots_e_b
  { x: 7.5, z: -4.0, w: 7.0, d: 0.7, h: 3.2, kind: "wall" }, // yard_n_a
  { x: 22.5, z: -4.0, w: 15.0, d: 0.7, h: 3.2, kind: "wall" }, // yard_n_b
  { x: 4.0, z: -18.5, w: 0.7, d: 13.0, h: 3.2, kind: "wall" }, // yard_w_a
  { x: 4.0, z: -6.0, w: 0.7, d: 4.0, h: 3.2, kind: "wall" }, // yard_w_b
  { x: -22.0, z: 9.5, w: 0.9, d: 0.9, h: 4.2, kind: "pillar" }, // chapel_colw0
  { x: -11.0, z: 9.5, w: 0.9, d: 0.9, h: 4.2, kind: "pillar" }, // chapel_cole0
  { x: -22.0, z: 13.5, w: 0.9, d: 0.9, h: 4.2, kind: "pillar" }, // chapel_colw1
  { x: -11.0, z: 13.5, w: 0.9, d: 0.9, h: 4.2, kind: "pillar" }, // chapel_cole1
  { x: -22.0, z: 17.5, w: 0.9, d: 0.9, h: 4.2, kind: "pillar" }, // chapel_colw2
  { x: -11.0, z: 17.5, w: 0.9, d: 0.9, h: 4.2, kind: "pillar" }, // chapel_cole2
  { x: -22.0, z: 21.0, w: 0.9, d: 0.9, h: 4.2, kind: "pillar" }, // chapel_colw3
  { x: -11.0, z: 21.0, w: 0.9, d: 0.9, h: 4.2, kind: "pillar" }, // chapel_cole3
  { x: -16.5, z: 22.0, w: 5.0, d: 1.4, h: 1.2, kind: "altar" }, // chapel_altar
  { x: -16.5, z: 23.9, w: 13.0, d: 0.9, h: 8.0, kind: "gable" }, // chapel_gable
  { x: -27.0, z: 15.0, w: 2.4, d: 3.2, h: 1.0, kind: "wall" }, // chapel_rubble
  { x: 10.5, z: 15.0, w: 4.8, d: 11.0, h: 3.6, kind: "tomb" }, // tomb0
  { x: 17.5, z: 15.0, w: 4.8, d: 11.0, h: 3.6, kind: "tomb" }, // tomb1
  { x: 24.5, z: 15.0, w: 4.8, d: 11.0, h: 3.6, kind: "tomb" }, // tomb2
  { x: -23.0, z: -21.0, w: 8.0, d: 0.5, h: 1.1, kind: "plot" }, // plot0_s
  { x: -23.0, z: -15.0, w: 8.0, d: 0.5, h: 1.1, kind: "plot" }, // plot0_n
  { x: -27.0, z: -18.0, w: 0.5, d: 6.0, h: 1.1, kind: "plot" }, // plot0_w
  { x: -11.5, z: -21.0, w: 8.0, d: 0.5, h: 1.1, kind: "plot" }, // plot1_s
  { x: -11.5, z: -15.0, w: 8.0, d: 0.5, h: 1.1, kind: "plot" }, // plot1_n
  { x: -15.5, z: -18.0, w: 0.5, d: 6.0, h: 1.1, kind: "plot" }, // plot1_w
  { x: -23.0, z: -12.0, w: 8.0, d: 0.5, h: 1.1, kind: "plot" }, // plot2_s
  { x: -23.0, z: -6.0, w: 8.0, d: 0.5, h: 1.1, kind: "plot" }, // plot2_n
  { x: -27.0, z: -9.0, w: 0.5, d: 6.0, h: 1.1, kind: "plot" }, // plot2_w
  { x: 22.0, z: -19.0, w: 8.0, d: 6.0, h: 3.0, kind: "shed" }, // shed
  { x: 14.5, z: -20.5, w: 3.4, d: 3.4, h: 2.2, kind: "shed" }, // lean_to
  { x: 24.0, z: -9.0, w: 6.0, d: 1.0, h: 1.4, kind: "plot" }, // yard_stack
  { x: 0.0, z: 0.0, w: 2.2, d: 2.2, h: 6.0, kind: "obelisk" }, // obelisk
  { x: -6.5, z: 8.0, w: 1.1, d: 1.1, h: 5.5, kind: "tree" }, // tree0
  { x: 6.5, z: -8.0, w: 1.1, d: 1.1, h: 5.5, kind: "tree" }, // tree1
  { x: -6.5, z: -20.0, w: 1.1, d: 1.1, h: 5.5, kind: "tree" }, // tree2
  { x: 6.5, z: 20.0, w: 1.1, d: 1.1, h: 5.5, kind: "tree" }, // tree3
];

/** Occluders derived from the blocks above — never hand-written. */
export const CEMETERY_STRUCTURES: Occluder[] = CEMETERY_BLOCKS.map((b) =>
  occ(b.x, b.z, b.w, b.d, b.h),
);

/**
 * Flush ground surfaces — paving laid at ground level, drawn with a negative
 * depth bias instead of being physically raised (a raised plane slices the
 * bottoms off props standing on it).
 *
 * No two entries here overlap at the same `zPri`. That is enforced by
 * tools/gen_cemetery.py and re-checked in tests/ground-overlap.test.mjs,
 * because two coplanar quads with the same bias flicker against each other
 * as the camera moves and there is nothing the renderer can do about it.
 */
export interface GroundSurface {
  x: number;
  z: number;
  w: number;
  d: number;
  /** Base colour. */
  hex: string;
  kind: "concrete" | "sand" | "grass";
  /** Depth bias. More negative draws in front. */
  zPri: number;
}

export const CEMETERY_FLOORS: GroundSurface[] = [
  { x: 0.0, z: 0.0, w: 8.0, d: 50.0, hex: "#4a4741", kind: "concrete", zPri: -1 }, // lane_ns
  { x: -17.0, z: 0.0, w: 26.0, d: 8.0, hex: "#4a4741", kind: "concrete", zPri: -1 }, // lane_w
  { x: 17.0, z: 0.0, w: 26.0, d: 8.0, hex: "#4a4741", kind: "concrete", zPri: -1 }, // lane_e
  { x: -17.0, z: 14.75, w: 25.0, d: 19.5, hex: "#4f4b45", kind: "concrete", zPri: -3 }, // floor_chapel
  { x: 17.0, z: 14.75, w: 25.0, d: 19.5, hex: "#3f3d39", kind: "concrete", zPri: -3 }, // floor_alley
  { x: -17.0, z: -14.75, w: 25.0, d: 19.5, hex: "#3d3a33", kind: "concrete", zPri: -3 }, // floor_plots
  { x: 17.0, z: -14.75, w: 25.0, d: 19.5, hex: "#4a3f31", kind: "sand", zPri: -3 }, // floor_yard
];

/** Places a jumpscare may come from — landmarks, not open ground. */
export const CEMETERY_SCARE_POINTS: Array<{ x: number; y: number; z: number }> = [
  { x: -16.5, y: 1.4, z: 22.0 },
  { x: -22.0, y: 2.2, z: 13.5 },
  { x: -27.0, y: 1.2, z: 15.0 },
  { x: 14.0, y: 2.4, z: 12.0 },
  { x: 21.0, y: 2.4, z: 18.0 },
  { x: 17.5, y: 3.0, z: 22.0 },
  { x: -23.0, y: 1.0, z: -18.0 },
  { x: -11.5, y: 1.0, z: -15.0 },
  { x: 10.5, y: 1.6, z: -8.5 },
  { x: 22.0, y: 3.2, z: -19.0 },
  { x: 0.0, y: 6.5, z: 0.0 },
];

/** Dead trees (x, z) — the client draws trunks and bare branches here. */
export const CEMETERY_TREES: Array<[number, number]> = [
  [-6.5, 8.0], [6.5, -8.0], [-6.5, -20.0], [6.5, 20.0],
];

export const HOLLOW_ROW: MapDefinition = {
  id: "hollow_row",
  displayName: "Hollow Row",
  tagline: "Four walled rooms around a crossing. Midnight, and fog.",
  theme: "cemetery",
  width: 60.0,
  depth: 50.0,
  wallHeight: 3.0,
  bounds: { minX: -30.0, maxX: 30.0, minZ: -25.0, maxZ: 25.0 },
  hunterSpawns: [
    { x: -3.0, y: 0, z: -22.5, ry: 0 },
    { x: -1.5, y: 0, z: -22.5, ry: 0 },
    { x: 0.0, y: 0, z: -22.5, ry: 0 },
    { x: 1.5, y: 0, z: -22.5, ry: 0 },
    { x: 3.0, y: 0, z: -22.5, ry: 0 },
    { x: -2.0, y: 0, z: -20.0, ry: 0 },
    { x: 0.0, y: 0, z: -20.0, ry: 0 },
    { x: 2.0, y: 0, z: -20.0, ry: 0 },
  ],
  propSpawns: [
    { x: -16.0, y: 0, z: 12.0, ry: Math.PI },
    { x: -13.0, y: 0, z: 20.0, ry: Math.PI },
    { x: 13.5, y: 0, z: 11.5, ry: Math.PI },
    { x: 21.0, y: 0, z: 17.5, ry: Math.PI },
    { x: -16.5, y: 0, z: -22.5, ry: Math.PI },
    { x: -25.5, y: 0, z: -12.8, ry: Math.PI },
    { x: 11.0, y: 0, z: -13.0, ry: Math.PI },
    { x: 25.0, y: 0, z: -23.0, ry: Math.PI },
  ],
  props: [
    { id: "c00", modelKey: "candelabra", x: -20.4, y: 0, z: 22.4, ry: 5.446 },
    { id: "c01", modelKey: "candelabra", x: -12.6, y: 0, z: 22.4, ry: 1.515 },
    { id: "c02", modelKey: "lantern", x: 14.0, y: 0, z: 8.6, ry: 3.964 },
    { id: "c03", modelKey: "lantern", x: 21.0, y: 0, z: 8.6, ry: 0.4 },
    { id: "c04", modelKey: "lantern", x: 14.0, y: 0, z: 21.4, ry: 1.896 },
    { id: "c05", modelKey: "lantern", x: 21.0, y: 0, z: 21.4, ry: 4.121 },
    { id: "c06", modelKey: "brazier", x: 14.0, y: 0, z: 22.6, ry: 4.264 },
    { id: "c07", modelKey: "brazier", x: 21.0, y: 0, z: 22.6, ry: 4.457 },
    { id: "c08", modelKey: "lantern", x: -5.2, y: 0, z: -19.0, ry: 5.31 },
    { id: "c09", modelKey: "lantern", x: 5.2, y: 0, z: 11.0, ry: 4.905 },
    { id: "c10", modelKey: "lantern", x: -5.2, y: 0, z: 17.0, ry: 1.155 },
    { id: "c11", modelKey: "lantern", x: 5.2, y: 0, z: -10.0, ry: 0.902 },
    { id: "c12", modelKey: "lantern", x: -18.0, y: 0, z: -5.3, ry: 5.44 },
    { id: "c13", modelKey: "lantern", x: 13.0, y: 0, z: 5.3, ry: 3.598 },
    { id: "c14", modelKey: "bench", x: -19.6, y: 0, z: 10.4, ry: 0.0 },
    { id: "c15", modelKey: "bench", x: -13.4, y: 0, z: 10.4, ry: 0.0 },
    { id: "c16", modelKey: "bench", x: -19.6, y: 0, z: 13.4, ry: 0.0 },
    { id: "c17", modelKey: "bench", x: -13.4, y: 0, z: 13.4, ry: 0.0 },
    { id: "c18", modelKey: "bench", x: -19.6, y: 0, z: 16.4, ry: 0.0 },
    { id: "c19", modelKey: "bench", x: -13.4, y: 0, z: 16.4, ry: 0.0 },
    { id: "c20", modelKey: "bench", x: -19.6, y: 0, z: 19.4, ry: 0.0 },
    { id: "c21", modelKey: "candelabra", x: -15.91, y: 0, z: 18.73, ry: 6.211 },
    { id: "c22", modelKey: "broken_pillar", x: -23.43, y: 0, z: 21.34, ry: 4.322 },
    { id: "c23", modelKey: "broken_pillar", x: -25.57, y: 0, z: 20.82, ry: 4.776 },
    { id: "c24", modelKey: "urn", x: -15.07, y: 0, z: 9.52, ry: 5.942 },
    { id: "c25", modelKey: "brazier", x: -8.12, y: 0, z: 14.56, ry: 3.381 },
    { id: "c26", modelKey: "skull", x: -25.24, y: 0, z: 15.42, ry: 2.546 },
    { id: "c27", modelKey: "bat", x: -17.05, y: 0, z: 20.26, ry: 4.877 },
    { id: "c28", modelKey: "sarcophagus", x: 8.42, y: 0, z: 21.87, ry: 1.498 },
    { id: "c29", modelKey: "sarcophagus", x: 19.09, y: 0, z: 22.19, ry: 5.773 },
    { id: "c30", modelKey: "angel_statue", x: 6.96, y: 0, z: 22.93, ry: 3.156 },
    { id: "c31", modelKey: "angel_statue", x: 20.95, y: 0, z: 12.07, ry: 3.909 },
    { id: "c32", modelKey: "gargoyle", x: 11.65, y: 0, z: 22.28, ry: 5.746 },
    { id: "c33", modelKey: "gargoyle", x: 27.78, y: 0, z: 18.61, ry: 3.713 },
    { id: "c34", modelKey: "coffin_open", x: 6.75, y: 0, z: 11.69, ry: 6.089 },
    { id: "c35", modelKey: "coffin_open", x: 27.45, y: 0, z: 22.53, ry: 2.742 },
    { id: "c36", modelKey: "raven", x: 14.19, y: 0, z: 18.05, ry: 6.113 },
    { id: "c37", modelKey: "raven", x: 22.49, y: 0, z: 8.9, ry: 1.483 },
    { id: "c38", modelKey: "grave_cross", x: 6.47, y: 0, z: 10.01, ry: 3.112 },
    { id: "c39", modelKey: "headstone", x: -25.27, y: 0, z: -16.65, ry: 0.039 },
    { id: "c40", modelKey: "headstone", x: -22.03, y: 0, z: -16.53, ry: -0.04 },
    { id: "c41", modelKey: "headstone", x: -25.43, y: 0, z: -19.32, ry: -0.017 },
    { id: "c42", modelKey: "headstone", x: -22.06, y: 0, z: -19.37, ry: -0.02 },
    { id: "c43", modelKey: "headstone", x: -13.84, y: 0, z: -16.43, ry: -0.019 },
    { id: "c44", modelKey: "headstone", x: -10.74, y: 0, z: -16.49, ry: -0.036 },
    { id: "c45", modelKey: "headstone", x: -13.98, y: 0, z: -19.3, ry: 0.014 },
    { id: "c46", modelKey: "headstone", x: -10.56, y: 0, z: -19.08, ry: 0.03 },
    { id: "c47", modelKey: "headstone", x: -25.36, y: 0, z: -7.54, ry: 0.026 },
    { id: "c48", modelKey: "headstone", x: -22.36, y: 0, z: -7.65, ry: -0.027 },
    { id: "c49", modelKey: "headstone", x: -25.43, y: 0, z: -10.23, ry: 0.034 },
    { id: "c50", modelKey: "headstone", x: -22.02, y: 0, z: -10.26, ry: -0.004 },
    { id: "c51", modelKey: "grave_sword", x: -6.29, y: 0, z: -17.74, ry: 3.572 },
    { id: "c52", modelKey: "grave_sword", x: -8.9, y: 0, z: -8.47, ry: 0.293 },
    { id: "c53", modelKey: "shield", x: -6.48, y: 0, z: -11.83, ry: 1.264 },
    { id: "c54", modelKey: "shield", x: -19.82, y: 0, z: -16.65, ry: 4.386 },
    { id: "c55", modelKey: "grave_cross", x: -15.17, y: 0, z: -12.14, ry: 0.475 },
    { id: "c56", modelKey: "grave_cross", x: -7.61, y: 0, z: -8.64, ry: 1.131 },
    { id: "c57", modelKey: "urn", x: -15.98, y: 0, z: -13.45, ry: 3.78 },
    { id: "c58", modelKey: "bone_pile", x: -8.74, y: 0, z: -12.24, ry: 4.093 },
    { id: "c59", modelKey: "skull", x: -7.01, y: 0, z: -9.58, ry: 1.53 },
    { id: "c60", modelKey: "lantern", x: -19.61, y: 0, z: -19.34, ry: 4.976 },
    { id: "c61", modelKey: "lantern", x: -11.85, y: 0, z: -22.3, ry: 4.003 },
    { id: "c62", modelKey: "grave_mound", x: 9.23, y: 0, z: -16.02, ry: 0.912 },
    { id: "c63", modelKey: "grave_mound", x: 23.53, y: 0, z: -10.62, ry: 1.502 },
    { id: "c64", modelKey: "grave_mound", x: 23.27, y: 0, z: -14.03, ry: 5.597 },
    { id: "c65", modelKey: "bone_pile", x: 20.2, y: 0, z: -13.29, ry: 0.766 },
    { id: "c66", modelKey: "bone_pile", x: 17.08, y: 0, z: -19.38, ry: 2.754 },
    { id: "c67", modelKey: "skeleton", x: 8.58, y: 0, z: -22.35, ry: 6.192 },
    { id: "c68", modelKey: "skeleton", x: 21.61, y: 0, z: -13.17, ry: 3.373 },
    { id: "c69", modelKey: "coffin", x: 23.26, y: 0, z: -7.17, ry: 1.2 },
    { id: "c70", modelKey: "coffin", x: 12.19, y: 0, z: -16.47, ry: 1.675 },
    { id: "c71", modelKey: "cauldron", x: 18.45, y: 0, z: -11.17, ry: 2.246 },
    { id: "c72", modelKey: "cauldron", x: 17.12, y: 0, z: -6.91, ry: 3.377 },
    { id: "c73", modelKey: "jack_o_lantern", x: 12.75, y: 0, z: -11.05, ry: 3.319 },
    { id: "c74", modelKey: "jack_o_lantern", x: 14.5, y: 0, z: -11.55, ry: 2.185 },
    { id: "c75", modelKey: "skull", x: 27.89, y: 0, z: -16.95, ry: 4.307 },
    { id: "c76", modelKey: "skull", x: 12.42, y: 0, z: -17.98, ry: 4.803 },
    { id: "c77", modelKey: "scarecrow", x: 11.86, y: 0, z: -21.66, ry: 1.61 },
    { id: "c78", modelKey: "scarecrow", x: 12.76, y: 0, z: -7.79, ry: 1.878 },
    { id: "c79", modelKey: "stone_well", x: 10.5, y: 0, z: -8.5, ry: 3.683 },
    { id: "c80", modelKey: "brazier", x: 21.07, y: 0, z: -6.9, ry: 2.068 },
    { id: "c81", modelKey: "raven", x: -3.08, y: 0, z: -15.75, ry: 0.63 },
    { id: "c82", modelKey: "raven", x: -0.48, y: 0, z: -5.16, ry: 2.687 },
  ],
  occluders: CEMETERY_STRUCTURES,
  scarePoints: CEMETERY_SCARE_POINTS,
};
